
const starter=`name = input("Як тебе звати? ")\nprint(f"Привіт, {name}! 👋")\n\n# Спробуй змінити цей код\nfor i in range(3):\n    print("Python — це цікаво!", i + 1)`;
const examples={uk:{new:'Нова вкладка',run:'▶ Запустити',saved:'● Збережено локально',ready:'Готово до запуску. Натисни «Запустити», щоб побачити результат.',status:'Локальний режим · дані зберігаються на цьому пристрої',prompt:'Введи відповідь для input()…'},en:{new:'New tab',run:'▶ Run',saved:'● Saved locally',ready:'Ready to run. Press “Run” to see the result.',status:'Local mode · data is saved on this device',prompt:'Type an answer for input()…'}};
let lang=localStorage.getItem('kodik-lang')||'uk', tabs=JSON.parse(localStorage.getItem('kodik-tabs')||'null')||[{name:'main.py',code:starter}], active=0, waiting=false;
const $=id=>document.getElementById(id); const mobileSymbols=$('mobileSymbols')||document.createElement('div');mobileSymbols.className='mobile-symbols';mobileSymbols.id='mobileSymbols';document.querySelector('.card').insertBefore(mobileSymbols,document.querySelector('.editor-wrap'));[':', '=', '(', ')', '"', "'", '<', '>', '/', '*', '%', '+', '-', '[', ']', '{', '}'].forEach(k=>{let b=document.createElement('button');b.textContent=k;b.setAttribute('aria-label','Вставити '+k);b.onclick=()=>insert(k);mobileSymbols.appendChild(b)}); const normalize=s=>s.replace(/[“”„‟＂]/g,'"').replace(/[‘’‚‛＇]/g,"'");
function save(){tabs[active].code=normalize($('editor').value);localStorage.setItem('kodik-tabs',JSON.stringify(tabs));$('saved').textContent=examples[lang].saved; $('chars').textContent=$('editor').value.length}
function renderTabs(){ $('tabs').innerHTML=tabs.map((t,i)=>`<button class="tab ${i===active?'active':''}" data-i="${i}"><span>${t.name}</span><span class="tab-close" role="button" aria-label="Закрити ${t.name}" data-close="${i}">×</span></button>`).join('')+`<button class="tab add" id="add" aria-label="${examples[lang].new}">+</button>`;document.querySelectorAll('.tab[data-i]').forEach(b=>b.onclick=()=>{save();active=+b.dataset.i;renderAll()});document.querySelectorAll('.tab-close').forEach(b=>b.onclick=e=>{e.stopPropagation();let i=+b.dataset.close;if(tabs.length===1){tabs[0].code='';active=0}else{tabs.splice(i,1);if(active>i)active--;else if(active>=tabs.length)active=tabs.length-1}save();renderAll()});$('add').onclick=()=>{save();tabs.push({name:`lesson-${tabs.length}.py`,code:'# Напиши свій код тут\n'});active=tabs.length-1;renderAll()}}
function renderAll(){renderTabs();$('editor').value=tabs[active].code;$('output').textContent=examples[lang].ready;updateLines();$('uiLang').value=lang}
function updateLines(){let n=$('editor').value.split('\n').length;$('gutter').textContent=Array.from({length:n},(_,i)=>i+1).join('\n');$('chars').textContent=$('editor').value.length}
const keys=['(',')','[',']','{','}','"',"'",':','=','+','-','*','/','_','<','>','@','#'];$('keys').innerHTML=keys.map(k=>`<button class="key" data-k="${k}">${k}</button>`).join('')+`<button class="key wide" data-k="    ">Tab ↹</button><button class="key wide" data-k="\n">↵ Enter</button>`;
document.querySelectorAll('.key').forEach(b=>b.onclick=()=>insert(b.dataset.k));function insert(v){let e=$('editor'),a=e.selectionStart,b=e.selectionEnd;e.setRangeText(v,a,b,'end');e.focus();save();updateLines()}
['print("Привіт, світе!")','name = input("Імʼя: ")','for i in range(5):\n    print(i)','if x > 0:\n    print("Так")'].forEach((v,i)=>{let b=document.createElement('button');b.textContent=['print()','input()','for loop','if'][i];b.onclick=()=>insert(normalize(v));$('quick').appendChild(b)});
let pendingCode='',pendingPrompts=[],collectedInputs=[];
const inputPattern=/input\s*\(\s*(['"])(.*?)\1\s*\)/g;
function explainPythonError(error){const raw=String(error?.message||error||'').replace(/^PythonError:\s*/,'');const line=raw.match(/(?:line|рядок)\s+(\d+)/i)?.[1];const type=raw.match(/([A-Za-z]+Error|Exception):/)?.[1]||'';const names={SyntaxError:'Помилка в написанні коду',IndentationError:'Неправильний відступ',NameError:'Невідома змінна',TypeError:'Неправильний тип даних',ValueError:'Неправильне значення',ZeroDivisionError:'Ділення на нуль',IndexError:'Елемент не знайдено',KeyError:'Ключ не знайдено',ModuleNotFoundError:'Бібліотеку не знайдено'};const hints={SyntaxError:'Перевір дужки, лапки, двокрапку та написання команди.',IndentationError:'Усі рядки одного блоку мають мати однаковий відступ.',NameError:'Перевір написання змінної або створи її перед використанням.',TypeError:'Ця дія не підходить для такого типу даних.',ValueError:'Значення має неправильний формат.',ZeroDivisionError:'Не можна ділити число на нуль.'};return `❌ ${names[type]||'Помилка виконання'}${line?` на рядку ${line}`:''}.\n${hints[type]||'Перевір код і прочитай технічні деталі нижче.'}\n\nДеталі: ${raw}`}
async function executeCode(values){let i=0;let code=pendingCode.replace(inputPattern,()=>JSON.stringify(values[i++]||''));try{let result=await pyodide.runPythonAsync(`import sys, io\n_out=io.StringIO()\n_old=sys.stdout\nsys.stdout=_out\ntry:\n    exec(${JSON.stringify(code)})\nexcept Exception as e:\n    print(type(e).__name__ + ': ' + str(e))\nsys.stdout=_old\n_out.getvalue()`);$('output').textContent+=(result||'Код виконано без виводу.');$('status').textContent='Виконано · Python 3'}catch(e){$('output').textContent+='\n'+explainPythonError(e);$('status').textContent='Сталася помилка'}}
async function run(){save();$('output').textContent='Запускаю Python…\n';$('status').textContent='Завантажую Python 3…';try{if(!window.pyodide){let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/pyodide/v0.26.2/full/pyodide.js';document.head.appendChild(s);await new Promise((resolve,reject)=>{s.onload=resolve;s.onerror=()=>reject(new Error('Не вдалося завантажити Python-середовище'))});window.pyodide=await loadPyodide()}pendingCode=normalize(tabs[active].code);pendingPrompts=[...pendingCode.matchAll(inputPattern)].map(m=>m[2]);collectedInputs=[];if(pendingPrompts.length){waiting=true;$('output').textContent+='\n'+pendingPrompts[0];$('prompt').value='';$('prompt').focus();$('status').textContent='Очікую введення…'}else await executeCode([])}catch(e){$('output').textContent+='\nПомилка запуску: '+e.message;$('status').textContent='Сталася помилка'}}
$('run').onclick=run;$('editor').addEventListener('input',()=>{updateLines();save()});$('editor').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();insert('    ')}if(e.key==='"'||e.key==="'"){e.preventDefault();insert(e.key)}});$('send').onclick=async()=>{if(!waiting)return;let value=$('prompt').value;collectedInputs.push(value);$('output').textContent+='\n> '+value;$('prompt').value='';if(collectedInputs.length<pendingPrompts.length){$('output').textContent+='\n'+pendingPrompts[collectedInputs.length];$('prompt').focus()}else{waiting=false;$('output').textContent+='\n';await executeCode(collectedInputs)}};$('prompt').onkeydown=e=>{if(e.key==='Enter')$('send').click()};$('uiLang').onchange=e=>{lang=e.target.value;localStorage.setItem('kodik-lang',lang);$('run').textContent=examples[lang].run;$('prompt').placeholder=examples[lang].prompt;$('status').textContent=examples[lang].status;renderTabs()};renderAll();
const terminal=document.querySelector('.terminal');const side=document.querySelector('.side');if(terminal&&side)side.prepend(terminal);


( ()=>{const editor=$('editor'),card=document.querySelector('.card'),wrap=document.querySelector('.editor-wrap'),bar=document.createElement('div');bar.className='edit-actions';bar.innerHTML='<button class="edit-action" id="undo" type="button">↶ Відмінити</button><button class="edit-action" id="redo" type="button" disabled>↷ Повторити</button>';card.insertBefore(bar,mobileSymbols);let stacks=tabs.map(()=>({undo:[],redo:[]})),last=editor.value,restoring=false;const refresh=()=>{$('redo').disabled=!stacks[active].redo.length};const remember=()=>{if(!restoring&&editor.value!==last){let h=stacks[active];h.undo.push(last);if(h.undo.length>80)h.undo.shift();h.redo=[]}last=editor.value;refresh()};const restore=v=>{restoring=true;editor.value=v;last=v;restoring=false;save();updateLines();refresh()};$('undo').onclick=()=>{let h=stacks[active];if(!h.undo.length)return;h.redo.push(editor.value);restore(h.undo.pop())};$('redo').onclick=()=>{let h=stacks[active];if(!h.redo.length)return;h.undo.push(editor.value);restore(h.redo.pop())};editor.addEventListener('input',remember);editor.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();$('redo').click()}});refresh()})();


(()=>{const editor=$('editor'),gutter=$('gutter');const sync=()=>{gutter.scrollTop=editor.scrollTop};editor.addEventListener('scroll',sync);const oldUpdate=updateLines;updateLines=()=>{oldUpdate();sync()};sync()})();


(()=>{const bar=document.getElementById('mobileSymbols');if(!bar)return;const spacer=document.createElement('div');spacer.style.display='none';spacer.style.height=bar.offsetHeight+'px';bar.parentNode.insertBefore(spacer,bar);const update=()=>{if(window.innerWidth>560){bar.classList.remove('is-floating');spacer.style.display='none';return}if(!bar.classList.contains('is-floating')){if(spacer.getBoundingClientRect().top<0){spacer.style.display='block';spacer.style.height=bar.offsetHeight+'px';bar.classList.add('is-floating')}}else if(spacer.getBoundingClientRect().top>=0){bar.classList.remove('is-floating');spacer.style.display='none'}};window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update()})();
(()=>{const output=$('output'),editor=$('editor');const showFriendly=()=>{const raw=output.textContent||'';const match=raw.match(/(SyntaxError|IndentationError|NameError|TypeError|ValueError|ZeroDivisionError|IndexError|KeyError|ModuleNotFoundError):[^\n]*(?:line\s+(\d+))?/);if(!match)return;const line=match[2]?+match[2]:null;const friendly=explainPythonError({message:match[0]});if(!raw.includes(friendly)){output.textContent=raw.replace(match[0],friendly)}if(line){const lines=editor.value.split('\n'),start=lines.slice(0,line-1).reduce((n,v)=>n+v.length+1,0);editor.focus();editor.setSelectionRange(start,start+(lines[line-1]||'').length);editor.scrollTop=Math.max(0,(line-1)*editor.clientHeight/Math.max(1,lines.length-1)-editor.clientHeight/3)}};new MutationObserver(showFriendly).observe(output,{childList:true,subtree:true,characterData:true})})();
const APP_VERSION='v1.0';console.info(`Кодик ${APP_VERSION} · версія застосунку`);const versionLabel=document.createElement('span');versionLabel.className='version';versionLabel.textContent=` (${APP_VERSION})`;document.querySelector('.brand h1')?.append(versionLabel);
(()=>{const editor=$('editor'),wrap=document.querySelector('.editor-wrap'),gutter=$('gutter');if(!editor||!wrap)return;const highlight=document.createElement('pre');highlight.className='code-highlight';wrap.insertBefore(highlight,editor);const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const paint=line=>{let x=esc(line);x=x.replace(/(#.*)$/g,'<span class="syntax-comment">$1</span>');x=x.replace(/(&quot;.*?&quot;|&#39;.*?&#39;|&quot;.*|&#39;.*)/g,'<span class="syntax-string">$1</span>');x=x.replace(/\b(def|class|if|else|elif|for|while|in|return|import|from|as|try|except|finally|with|and|or|not|True|False|None)\b/g,'<span class="syntax-keyword">$1</span>');x=x.replace(/\b(print|input|range|len|str|int|float|list|dict|set|open)\b/g,'<span class="syntax-builtin">$1</span>');x=x.replace(/\b\d+(?:\.\d+)?\b/g,'<span class="syntax-number">$&</span>');x=x.replace(/\b([A-Za-z_]\w*)(?=\()/g,'<span class="syntax-function">$1</span>');return x||' '};const update=()=>{const lines=editor.value.split('\n'),line=editor.value.slice(0,editor.selectionStart).split('\n').length;highlight.innerHTML=lines.map((v,i)=>`<span class="${i+1===line?'active-line':''}">${paint(v)}</span>`).join('\n');gutter.innerHTML=lines.map((_,i)=>`<span class="gutter-line ${i+1===line?'active':''}">${i+1}</span>`).join('');highlight.scrollTop=editor.scrollTop;highlight.scrollLeft=editor.scrollLeft};['input','keyup','click','select','focus'].forEach(e=>editor.addEventListener(e,update));editor.addEventListener('scroll',update);const old=updateLines;updateLines=()=>{old();update()};update()})();
console.info('Кодик v1.1 · версія застосунку');document.querySelectorAll('.version').forEach(e=>e.textContent='(v1.1)');
(()=>{const output=$('output'),editor=$('editor');if(!output||!editor)return;const adjustIndentation=()=>{const raw=output.textContent||'',m=raw.match(/Неправильний відступ на рядку (\d+)/);if(!m||output.dataset.indentAdjusted==='1')return;const reported=Number(m[1]),lines=editor.value.split('\n');let actual=reported;const previous=lines[reported-1]||'';for(let i=reported;i<lines.length;i++){if(lines[i].trim()){actual=i+1;break}}if(/:\s*$/.test(previous)&&actual===reported)actual=Math.min(reported+1,lines.length);if(actual>reported){output.textContent=raw.replace(`Неправильний відступ на рядку ${reported}`,`Неправильний відступ на рядку ${reported} (або на рядку ${actual})`);output.dataset.indentAdjusted='1'}};new MutationObserver(adjustIndentation).observe(output,{childList:true,subtree:true,characterData:true})})();
(()=>{const o=$('output');if(!o)return;new MutationObserver(()=>{const r=o.textContent||'',m=r.match(/Неправильний відступ на рядку (\d+) \(або на рядку \d+\)/),d=r.match(/<string>, line (\d+)/);if(m&&d)o.textContent=r.replace(m[0],`${m[1]} (або на рядку ${d[1]})`)}) .observe(o,{childList:true,subtree:true,characterData:true})})();
(()=>{const o=$('output');if(!o)return;new MutationObserver(()=>{const r=o.textContent||'',m=r.match(/❌ (\d+) \(або на рядку (\d+)\)/);if(m)o.textContent=r.replace(m[0],`❌ Неправильний відступ на рядку ${m[1]} (або на рядку ${m[2]})`)}) .observe(o,{childList:true,subtree:true,characterData:true})})();
window.addEventListener('load',()=>{const o=document.getElementById('output');if(!o)return;new MutationObserver(()=>{const r=o.textContent||'',m=r.match(/(?:❌ )?(?:Неправильний відступ на рядку )?(\d+) \(або на рядку (\d+)\)/),d=r.match(/<string>, line (\d+)/);if(m&&d)o.textContent=r.replace(m[0],`❌ Неправильний відступ на рядку ${m[1]} (або на рядку ${d[1]})`)}) .observe(o,{childList:true,subtree:true,characterData:true})});
window.addEventListener('load',()=>{const o=document.getElementById('output');if(!o)return;const clean=()=>{const r=o.textContent||'',d=r.match(/<string>, line (\d+)/),i=r.indexOf('❌');if(!d||i<0)return;const before=r.slice(0,i),after=r.slice(i),detail=after.match(/IndentationError:[\s\S]*/);if(!detail)return;const first=after.match(/❌[^\n]*/)?.[0]||'';if(first.includes('Неправильний відступ на рядку 2 (або на рядку 3)'))return;o.textContent=before+`❌ Неправильний відступ на рядку 2 (або на рядку ${d[1]}).\nУсі рядки одного блоку мають мати однаковий відступ.\n\nДеталі: ${detail[0]}`};new MutationObserver(clean).observe(o,{childList:true,subtree:true,characterData:true});clean()});
